version: "3"

services:
  frontend:
    container_name: fffrontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: imagefffrontend
    ports:
      - "3000:3000"
  backend:
    container_name: ffbackend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: imageffbackend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"