version: "3"

services:
  frontend:
    container_name: fffrontend
    image: vertfromage/fffrontend:latest
    ports:
      - "80:3000"
      - "443:3000"
  backend:
    container_name: ffbackend
    image:  vertfromage/ffbackend:latest
    ports:
      - "4000:4000"
    env_file:
      - ./.env